# Mod Properties
mod_id=thermal_expansion
mod_name=Thermal Expansion
mod_version=11.0.2

# Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Platform Properties
java_version=25
mc_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

# Dependency Properties
cofh_core_version=11.0.2
cofh_core_max_version=11.1.0

thermal_core_version=11.0.7
thermal_core_max_version=11.1.0

jei_version=29.40.0.101
#patchouli_version=1.18.2-67

# Publishing Properties

# Options: alpha, beta, release
release_type=release